project:
  type: website
  output-dir: docs

website:
  title: "Angela's Spherical Cow"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example_analysis.qmd
        text: Example analysis

format:
  html:
    theme: sandstone ## minty also good
    css: styles.css
    toc: true

editor: visual

